import Head from 'next/head'

export default function DataFlow(props: any) {
  return (
    <>
      <Head>
        <title>Wynn Las Vegas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="shortcut icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>DataFlow</div>
      </main>
    </>
  )
}
