import Head from 'next/head'
import { client } from '@/lib/contentful/client';
import { useEffect } from 'react'
import { GetStaticProps} from 'next';

export default function Home(props:any) {
  useEffect(() => {
    document.querySelector("body")?.classList.add("home")
  })

  return (
    <>
      <Head>
        <title>Wynn Las Vegas</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="shortcut icon" href="/favicon.ico" />
      </Head>
      <main>
        <div>Home page</div>
      </main>
    </>
  )
}
